version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - proximity_service_app
  proximity_service_app:
    container_name: proximity_service_app
    image: imsharyan/proximity_service:1.0.0
    build: .
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - proximity_service_db
  proximity_service_db:
    container_name: proximity_service_db
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env.prod.db
    volumes:
      - proximity_service_db_data:/var/lib/postgresql/data

volumes:
  proximity_service_db_data: {}