version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: |
            echo "installing dependencies"
            python -m pip install -r requirements.txt
      - run: |
            echo "running linter"
            python -m pylint src/
      - run: |
            echo "running tests"
            python -m pytest
  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: echo "Building docker image"

workflows:
  dev-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
  prod-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master