version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: make install-deps
      - run: make linting
      - run: make test

  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: echo "Building docker image"

workflows:
  dev-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
  prod-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master