version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make install-deps
      - run:
          name: Linting
          command: make linting
      - run:
          name: Testing
          command: make test

  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: set config
          command: |
            ( set -o posix ; export -p ) | grep 'APP_ENV\|SQLALCHEMY_DATABASE_URI_PROD' > .env.prod
            ( set -o posix ; export -p ) | grep 'POSTGRES_DB\|POSTGRES_USER\|POSTGRES_PASSWORD' > .env.prod.db
      - run:
          name: Image creation
          command: |
            echo "Image creation in progress.."
            docker-compose build --no-cache
            echo "Image creation done."
      - run:
          name: Docker login
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
      - run:
          name: Docker push
          command: |
            echo "Pushing docker image to dockerhub"
            docker-compose push

workflows:
  dev-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
  prod-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master